# Generated by Django 4.0.4 on 2022-05-05 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingMedicalPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_age', models.PositiveIntegerField()),
                ('rf_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=255)),
                ('rf_bmi', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rf_children', models.PositiveIntegerField()),
                ('rf_is_smoker', models.BooleanField()),
                ('rf_region', models.CharField(choices=[('northwest', 'North West'), ('northeast', 'North East'), ('southeast', 'South East'), ('southwest', 'South West')], max_length=255)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
