# Generated by Django 4.0.4 on 2022-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existing_premiums_api', '0002_alter_existingmedicalpremium_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingmedicalpremium',
            name='premium',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
