# Generated by Django 4.0.4 on 2022-05-07 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existing_premiums_api', '0005_alter_existingmedicalpremium_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingmedicalpremium',
            name='rf_bmi',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
